name: example-environment
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.8
    - pytorch=1.5
    - torchvision=0.6
    - cudatoolkit=10.1
    - tqdm
    - tensorboard
    - numpy
    - matplotlib
    - seaborn
    - scikit-learn
    - pip
    - pip:
        - thop==0.0.31-2001170342
